apiVersion: civo.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-civo
spec:
  region: "LON1"
  credentials:
    source: Secret
    secretRef:
      name: civo-creds
      namespace: crossplane-system
      key: credentials
