---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-providers
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./crossplane/gcp/providers
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-example
