apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bucket-user-composition-iam
  labels:
    crossplane.io/xrd: xbucketusers.crossplane.upsider.dev
    provider: AWS
spec:
  compositeTypeRef:
    apiVersion: crossplane.upsider.dev/v1alpha1
    kind: XBucketUser
  writeConnectionSecretsToNamespace: crossplane-system
  patchSets:
    - name: preventDeletion
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.preventDeletion
          toFieldPath: spec.deletionPolicy
          transforms:
            - type: convert
              convert:
                toType: string
            - type: map
              map:
                "true": Orphan
                "false": Delete
  resources:
    - name: iam
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: User
        metadata:
          name: unknown # To be overridden
        spec:
          forProvider:
            tags:
              - key: Managed-by
                value: Crossplane
              - key: Name
                value: unknown # To be overridden

      patches:
        - type: PatchSet
          patchSetName: preventDeletion

        - fromFieldPath: metadata.name
          toFieldPath: metadata.name

        - fromFieldPath: spec.providerConfigRef
          toFieldPath: spec.providerConfigRef.name

        - fromFieldPath: metadata.name
          toFieldPath: "spec.forProvider.tags[1].value"
    - name: iam-policy
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: Policy
        metadata:
          name: unknown # To be overridden
        spec:
          forProvider:
            name: unknown # To be overridden
            document: | # To be overridden

      patches:
        - type: PatchSet
          patchSetName: preventDeletion

        - fromFieldPath: spec.providerConfigRef
          toFieldPath: spec.providerConfigRef.name

        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "policy-for-%s"

        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.name
          transforms:
            - type: string
              string:
                fmt: "policy-for-%s"

        - type: CombineFromComposite
          combine:
            strategy: string
            variables:
              - fromFieldPath: spec.bucketName
              - fromFieldPath: spec.bucketName
            string:
              fmt: |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                        "Sid": "sid01",
                        "Effect": "Allow",
                        "Action": [
                            "s3:PutObject",
                            "s3:GetObject",
                            "s3:GetObjectVersion",
                            "s3:DeleteObject",
                            "s3:DeleteObjectVersion"
                        ],
                        "Resource": ["arn:aws:s3:::%s/*"]
                    },
                    {
                        "Sid": "sid02",
                        "Effect": "Allow",
                        "Action": [
                            "s3:ListBucket",
                            "s3:ListBucketVersions"
                        ],
                        "Resource": ["arn:aws:s3:::%s"]
                    }
                  ]
                }
          toFieldPath: spec.forProvider.document
    - name: iam-policy-attachment
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: UserPolicyAttachment
        metadata:
          name: unknown # To be overridden
        spec:
          forProvider:
            policyArnRef:
              name: unknown
            userNameRef:
              name: unknown
      patches:
        - type: PatchSet
          patchSetName: preventDeletion

        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "policy-attachment-for-%s"

        - fromFieldPath: spec.providerConfigRef
          toFieldPath: spec.providerConfigRef.name

        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.policyArnRef.name
          transforms:
            - type: string
              string:
                fmt: "policy-for-%s"

        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.userNameRef.name
