---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    semver: v0.34.0
  url: https://github.com/fluxcd/flux2
